const { USER_ROLES, BOOKING_STATUS, TIME_SLOTS, PRICE_UNITS, GST_RATE, SERVICE_CATEGORIES, SOCKET_EVENTS, INDIAN_CITIES } = require('./constants');

module.exports = {
  USER_ROLES,
  BOOKING_STATUS,
  TIME_SLOTS,
  PRICE_UNITS,
  GST_RATE,
  SERVICE_CATEGORIES,
  SOCKET_EVENTS,
  INDIAN_CITIES,
};
